### ISSUE TITLE
verlag font

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#11]
Hi DP,

Noticing that Verlag is being used as the sans serif font int he top nav. it should be Avenir. You need that font info again?

thx!

**Comment by pollardld** [comment]
Nope, got the fonts. Sorry about that. The splash page used Verlag and I forgot to switch that out for Avenir. Fixing now. @sarahmagrish

**Comment by pollardld** [comment]
Avenir is now working correctly. 

I added some classes you can use to apply the fonts through html, other option is to add the fonts in the css. @sarahmagrish I can show you how to do this or I can add them.

The classes are:
```
.AvenirLTStd-Heavy { 
  font-family: AvenirLTStd-Heavy; 
}
.AvenirLTStd-Book { 
  font-family: AvenirLTStd-Book; 
}
.AvenirLTStd-MediumOblique { 
  font-family: AvenirLTStd-MediumOblique; 
}
.AvenirLTStd-BookOblique { 
  font-family: AvenirLTStd-BookOblique; 
}
.AvenirLTStd-Medium { 
  font-family: AvenirLTStd-Medium; 
}
.AvenirLTStd-BlackOblique { 
  font-family: AvenirLTStd-BlackOblique; 
}
.AvenirLTStd-Black { 
  font-family: AvenirLTStd-Black; 
}
.AvenirLTStd-HeavyOblique { 
  font-family: AvenirLTStd-HeavyOblique; 
}
```
