### ISSUE TITLE
smart sliders

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#13]
Hi David,

Did you make settings for the text anywhere for the smart sliders or should I be creating them from scratch? Can't quite tell there. I can see how to create them but don't want to redo the styling if you already did it. also if we do decide to use sentinel and avenir how would i do that? would i need to add that to the CSS?

thx!
Sarah

**Comment by pollardld** [comment]
@sarahmagrish 

Bad news, looks like smart sliders have there own font settings as well 😫. Which cool in most cases, but not ours. 

Good news, it is super easy to customize and so we can use sentinel and avenir 😃 .

I added a test title to the [home page slider](http://63y.ea8.mwp.accessdomain.com/) and it is working. 
My steps were: 

1. Choose the slider you want to edit

2. Hover over the thumbnail and select edit
   <img width="250" alt="screen shot 2018-03-14 at 5 29 01 pm" src="https://user-images.githubusercontent.com/2632164/37438221-712b68ea-27ae-11e8-9c48-f1bc86b242d6.png" ><img width="302" alt="screen shot 2018-03-14 at 5 28 53 pm" src="https://user-images.githubusercontent.com/2632164/37438223-73c37d86-27ae-11e8-8bdb-acf89b8c5418.png">

3. Add a layer that contains text (*e.g.*, header)
    <img width="300" alt="screen shot 2018-03-14 at 5 29 45 pm" src="https://user-images.githubusercontent.com/2632164/37438256-9e6352aa-27ae-11e8-9cd4-abc1d901f669.png">

4. Select the paint bucket tab from the modal that pops up
   <img width="300" alt="screen shot 2018-03-14 at 5 30 43 pm" src="https://user-images.githubusercontent.com/2632164/37438257-a1b72ed6-27ae-11e8-8dfc-5088116cd168.png">

5. In the family input add the font you want to use (i have the default set to "Sentinel A", "Sentinel B")

*Note: the correct font will not show up while editing the slider, but once saved the font will be correct when viewing the webpage containing the slider*

**Comment by sarahmagrish** [comment]
nice! can you show me how to change it to avenir to test that look out? also, where should I mess around with the type size? thank you.

**Comment by pollardld** [comment]
In the Family input add one of the following:

AvenirLTStd-Heavy
AvenirLTStd-Book
AvenirLTStd-MediumOblique
AvenirLTStd-BookOblique
AvenirLTStd-Medium
AvenirLTStd-BlackOblique
AvenirLTStd-Black
AvenirLTStd-HeavyOblique

<img width="435" alt="screen shot 2018-03-16 at 12 08 49 pm" src="https://user-images.githubusercontent.com/2632164/37540083-fd3f6786-2912-11e8-8a2a-c62208c745e3.png">
