### ISSUE TITLE
CSS fonts

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#15]
Possible to show me how to edit these in CSS? Would love to have that flexibility -- just for myself. thx!

**Comment by pollardld** [comment]
For sure, it would probably be easiest show you in person then document it here @sarahmagrish

**Comment by sarahmagrish** [comment]
Sweet -- thank you! Would sometime tomorrow (Tuesday) work for you? I am pretty wide open after 11 am except from 1 - 2.

**Comment by pollardld** [comment]
**HTML**  

sentinel : `class="sentinel"`  
*e.g.*: 
```html
<div class="sentinel"></div>
```

avenir book : `class="AvenirLTStd-Book"`
avenir book oblique : `class="AvenirLTStd-BookOblique"`
avenir medium : `class="AvenirLTStd-Medium"`
avenir medium oblique : `class="AvenirLTStd-MediumOblique"`
avenir black : `class="AvenirLTStd-Black"`
avenir black oblique : `class="AvenirLTStd-BlackOblique"`
avenir heavy : `class="AvenirLTStd-Heavy"`
avenir heavy oblique : `class="AvenirLTStd-HeavyOblique"`

```html
<div class="AvenirLTStd-Heavy"></div>
```
___  

**CSS**  

*see Custom CSS in WP Admin*
*e.g.*:
```css
  font-family: "Sentinel A", "Sentinel B";
  font-family: AvenirLTStd-HeavyOblique; 
  font-size: 1em;
  font-style: italic;
  font-weight: normal;
  letter-spacing: 0.18375em;
  line-height: 1.75em;
```
