### ISSUE TITLE
top nav styling

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#17]
Hi David, Can I style the top nav myself? Looking to add word spacing and padding between items. I can be more specific if you need to do it otherwise happy to tweak it on my own. thx!

**Comment by pollardld** [comment]
You style a good amount of it @sarahmagrish 

**To edit text, pages, etc**:

  1.  Appearance -> Menus
     <img width="160" alt="screen shot 2018-03-20 at 2 50 51 pm" src="https://user-images.githubusercontent.com/2632164/37684822-80f63a9e-2c4e-11e8-8468-1a6b6b99cca9.png">
  2. Select the menu you want to edit
    <img width="400" alt="screen shot 2018-03-20 at 2 50 59 pm" src="https://user-images.githubusercontent.com/2632164/37684838-931fd1d0-2c4e-11e8-8333-44195a8d63c9.png">
  3. Edit 
    <img width="400" alt="screen shot 2018-03-20 at 2 51 08 pm" src="https://user-images.githubusercontent.com/2632164/37684853-9a6d6b5a-2c4e-11e8-90b5-b8643e02d816.png">

**For all other editing**: 

  1. Appearance -> Theme Settings
    <img width="160" alt="screen shot 2018-03-20 at 2 52 34 pm" src="https://user-images.githubusercontent.com/2632164/37684883-b3b620f2-2c4e-11e8-91c7-c1d004b8a0a3.png">
  2. Select Header from left menu
    <img width="300" alt="screen shot 2018-03-20 at 2 52 44 pm" src="https://user-images.githubusercontent.com/2632164/37684889-ba4ec84c-2c4e-11e8-849c-33756fc9e112.png">
