### ISSUE TITLE
footer editing spots?

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#18]
hiya, I sniffed out some footer styling in the custom CSS and in the menus area but not seeing how to edit other footer elements. can you point me in the right direction? I'm here til 5 if that helps. thx!

**Comment by sarahmagrish** [comment]
update! 

Laura showed me the spot in widgets where I can edit more stuff. So now my more specific question is: how do we style the e-news sign up?

thx!

**Comment by pollardld** [comment]
sorry we didn't go over that. Thank you @ldford 🍾 

e-news styles would be under Settings -> [Mailchimp Setup](http://63y.ea8.mwp.accessdomain.com/wp-admin/options-general.php?page=mailchimpSF_options)  

<img width="200" alt="screen shot 2018-03-23 at 11 13 51 am" src="https://user-images.githubusercontent.com/2632164/37846618-6a786604-2e8b-11e8-908d-07910feba1d5.png">

**Comment by sarahmagrish** [comment]
thx! could we look at this one side-by-side for a sec? not making much headway on my own.
