### ISSUE TITLE
favicon 

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#2]
thanks for adding! it is blurry though - need anything from me on that?

**Comment by pollardld** [comment]
Thanks for catching that. if you are cool with the redd logo as the favicon, then I can just add a higher resolution version. stick with the redd logo as the favicon @sarahmagrish ?

**Comment by sarahmagrish** [comment]
Yes – love the red redd logo up there! thx

## 

Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209x-apple-data-detectors://11/1
‪M (971) 344.7595tel:(971)%20344.7595 | www.ecotrust.orghttp://www.ecotrust.org/

Please note that I am out on Fridays.

**Comment by pollardld** [comment]
higher resolution favicon added
