### ISSUE TITLE
search

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#20]
can you outline what the search options are? trying to understand how I should provide styling / direction there. thx!

**Comment by pollardld** [comment]
The options for search are kind of confusing and not well documented for the theme. 
The only search things i see are a widget and the theme option to turn search on in the header. And the later does not seem to work as expected.

One option (and the way I have it set up now) is to use a page for search. 
  - A nav item to the search page
  - The [search page](http://63y.ea8.mwp.accessdomain.com/search/) contains a search box (and a shorter hero image so you can see the search box right away)
  - Search results open in new page formatted by the theme

We can try figure out a better way depending on your thoughts about the option above. @sarahmagrish

**Comment by sarahmagrish** [comment]
yeah -- search kinda sucks huh?! The results it returns look pretty weird too. 

I think we should just table styling the results until the next round of work on this. 

I did try to style the search page a bit and it is looking ok.
http://63y.ea8.mwp.accessdomain.com/search/

 Two things: Possible to ditch the small "search" text and divider line associated with the widget?

Also possible to make the search box white instead of transparent grey? Guessing that is all custom CSS and out of my current league.

thx!

**Comment by pollardld** [comment]
looks great! 

search text is ditched and input in white.
