### ISSUE TITLE
contact section on venue page

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#21]
hi DP,

this is pretty different than the wireframes -- is this your rec for how we make the theme fit the bill?  I think they could work but we might need to find a way to make them all show at once and not be subject to viewing by slider. 

Thoughts? @ldford what do you think?

thx,
Sarah

**Comment by sarahmagrish** [comment]
oops update is that Laura was messing around there! I think you can ignore this one for now DP and we will try to straighten it out ourselves.

**Comment by sarahmagrish** [comment]
Just noticing that one of the "Content elements" is a team member. That may be just what we need but haven't messed around with it yet. Don't think it shows up on the "Haven" demo

**Comment by pollardld** [comment]
Your right, I don't think team member is used in the haven demo. @sarahmagrish 

Here is the docs on how it: [Team Member Docs](http://docs.themefuse.com/the-core/your-theme/shortcodes/team-member-1)
