### ISSUE TITLE
hub page gallery styling

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#24]
Looking at this page: http://63y.ea8.mwp.accessdomain.com/hub/

And looking at the gallery at the bottom of the page. Is there any way to control the styling that you see on mouse over of the images? 

Ideally we could just get rid of the white overlay and the text since I will need to add text to these images myself for them to display without mousing over them.

Other suggestions welcome too!

**Comment by sarahmagrish** [comment]
Or actually if there was a way to just have an excerpt show that would be cool. I'd prefer a dark overlay to a white overlay if we can.

**Comment by pollardld** [comment]
All the options can be found under Appearance -> Theme Settings -> Posts -> Portfolio.

Here are the docs for that: 
http://docs.themefuse.com/the-core/your-theme/portfolio/changing-the-projects-display-type-and-style-1
http://docs.themefuse.com/the-core/your-theme/portfolio/how-to-display-your-projects-on-the-front-end-1

**Comment by sarahmagrish** [comment]
thanks!!
