### ISSUE TITLE
gallery 

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#25]
I can see a subtitle displayed here http://jkj.c37.mwp.accessdomain.com/?page_id=13

but can't seem to get it to display on mouse over here: http://63y.ea8.mwp.accessdomain.com/hub/

I tried the docs you linked to but could't get it to work. help? thanks!

Also hoping to use the style on the theme -- the gray box behind the image gallery but I can't figure that one out either.

**Comment by sarahmagrish** [comment]
hiya! that "Excerpt" field is displaying now -- thanks! But it seems to have a really limited word count. See attached screenshot. Possible to fix that? Also still hoping to get that gray box behind the gallery like the haven theme has but not sure how to do it.

<img width="485" alt="screen shot 2018-03-27 at 11 52 21 am" src="https://user-images.githubusercontent.com/4765127/37988360-929f2c44-31b5-11e8-90c5-d614790fc6af.png">

**Comment by pollardld** [comment]
I should be able to overwrite the excerpt length. will give that a go now. @sarahmagrish

**Comment by pollardld** [comment]
fixed @sarahmagrish 

let me know if you want any additional style changes

**Comment by sarahmagrish** [comment]
Shoot -- not seeing the longer excerpts. 

![screen shot 2018-03-27 at 2 49 18 pm](https://user-images.githubusercontent.com/4765127/37996875-0f57c65c-31ce-11e8-98d0-d95ed5a3c8d8.png)

something else i should do?

**Comment by sarahmagrish** [comment]
Now it is working! thanks. one last question here -- do you know how I control the order or the portfolio items on the hub page? 

I thought it might be here but it doesn't seem to work.

![screen shot 2018-03-27 at 3 07 30 pm](https://user-images.githubusercontent.com/4765127/37997715-af2f9d24-31d0-11e8-839e-a5db64156d5f.png)

**Comment by pollardld** [comment]
Looks like they are ordered by published date. Newest to oldest. You can edit that quickly through 'Quick Edit' for example:

<img width="800" alt="screen shot 2018-03-27 at 5 29 57 pm" src="https://user-images.githubusercontent.com/2632164/38001971-a2c1b702-31e4-11e8-84f3-3281bf4efdd1.png">

<img width="400" alt="screen shot 2018-03-27 at 5 31 25 pm" src="https://user-images.githubusercontent.com/2632164/38002003-bedd041e-31e4-11e8-84ff-29b4eab2ec23.png">

**Comment by sarahmagrish** [comment]
ok thx! working
