### ISSUE TITLE
home page top image text off center

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#27]
this is the weird bug that showed up yesterday when we were working together. not sure why!

**Comment by pollardld** [comment]
quick fix. padding of 150px was applied to the text in the smart slider settings 

<img width="386" alt="screen shot 2018-03-27 at 2 30 51 pm" src="https://user-images.githubusercontent.com/2632164/37996156-93d8d8ba-31cb-11e8-8c1d-39e8eb95adbc.png">

**Comment by sarahmagrish** [comment]
thanks! i added that to get the lines be shorter. taking the padding away makes it break funny: 


![screen shot 2018-03-27 at 2 55 39 pm](https://user-images.githubusercontent.com/4765127/37997159-fc661926-31ce-11e8-83d6-509c291db523.png)

ideas on how to still accomplish the break?

**Comment by pollardld** [comment]
my bad. 
we can just add padding to both sides of the title. I added padding of 150px to the left and right of the title. If that is too much we can bump it down however we needed. @sarahmagrish

**Comment by sarahmagrish** [comment]
looking good - thx!
