### ISSUE TITLE
Enews block styling

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#28]
this needs to be wrapped up and we need documentation on how to drop it in on other pages (ok if you need to do that but we should document that)

**Comment by pollardld** [comment]
Wrapped up. I created a section template named 'Newsletter Signup' that you can drop into any other page. @sarahmagrish 

<img width="433" alt="screen shot 2018-03-27 at 6 08 52 pm" src="https://user-images.githubusercontent.com/2632164/38002938-fa2ebbe8-31e9-11e8-9406-56dd43e4e493.png">

**Comment by sarahmagrish** [comment]
wow rad. thx!
