### ISSUE TITLE
tenant page breadcrumb

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#29]
can you suppress this breadcrumb? I think I can add in a "Back to Hub" button in it's place myself.

<img width="506" alt="screen shot 2018-03-27 at 1 05 29 pm" src="https://user-images.githubusercontent.com/4765127/37992077-9f49d3fe-31bf-11e8-9ccd-ba39b6f5eb14.png">

See http://63y.ea8.mwp.accessdomain.com/project/tenant-one/ for reference.

**Comment by pollardld** [comment]
breadcrumb suppressed.
