### ISSUE TITLE
word spacing with sentinel in CSS?

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#30]
Hi David, I am trying to figure out if it is possible to set some global word spacing for sentinel in the CSS. Is word spacing a common style tool? Not letter spacing to be clear. Any issues with trying it? thx!

**Comment by pollardld** [comment]
yes you can use `word-spacing` property, *e.g.,* `word-spacing: 0px;` @sarahmagrish

**Comment by sarahmagrish** [comment]
thx!
