### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#33]
this is missing obviously -- don't know that it is your job but tracking that here!

**Comment by pollardld** [comment]
Thanks for adding this. Will can set up the tracking for this as soon as we promote the site from 63y.ea8.mwp.accessdomain.com to reddonsalmon.com

**Comment by ldford** [comment]
@pollardld I think we should use the Yoast plugin for Redd on Salmon. It works well and the consistency would be nice. Can you add?

**Comment by pollardld** [comment]
sounds good. will add @ldford
