### ISSUE TITLE
newsletter sign up block

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#34]
content not quite responsive -- needs to show up stacked on mobile with smaller font size

<img width="399" alt="screen shot 2018-04-03 at 2 52 48 pm" src="https://user-images.githubusercontent.com/4765127/38277858-c37901ac-374e-11e8-859f-18ee46d2e89e.png">

**Comment by pollardld** [comment]
👀 Thanks for catching!  @sarahmagrish
