### ISSUE TITLE
drop down menus in top nav

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#35]
can you remind me how to turn these on and off? thx!

**Comment by pollardld** [comment]
Even though it looks like you already got this, I am documenting below:

1. Choose 'Menus' under 'Appearance' in the WP left menu
2. Select one of the two top navs from the dropdown of menu options and hit the 'select' button
3. Delete any nav items that are nested under a parent menu item

**Comment by sarahmagrish** [comment]
oops I was unclear! I wanted to see what it looked like to add them back in. Request from Jeanne -- just to test it on venue. Possible?

**Comment by pollardld** [comment]
Yep and simple to do: @sarahmagrish 

  1. Choose 'Menus' under 'Appearance' in the WP left menu
  2. Select a nav from the dropdown
  3. Choose a page to add from the left panel of options 
    <img width="300" alt="screen shot 2018-04-17 at 4 25 10 pm" src="https://user-images.githubusercontent.com/2632164/38903877-ee6ce35c-425b-11e8-81cf-f1ad497b3f16.png">
  4. Select 'Add to Menu'
  5. Drap and drop where you want them in the menu structure tree  
  6. Save
<img width="350" alt="screen shot 2018-04-17 at 4 26 22 pm" src="https://user-images.githubusercontent.com/2632164/38903911-1e34cf6e-425c-11e8-930b-7ddca8996071.png">
