### ISSUE TITLE
font size on quote attribution

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#4]
"—Amanda Oborne, Ecotrust's Vice President of Food & Farms" could come down a bit in font size - looks like it is 22px on desktop now. Maybe 15px?

**Comment by pollardld** [comment]
made the text 15px on small to medium desktop screens and 16px on large desktop screens.

**Comment by pollardld** [comment]
super sorry, i should not have closed this issue or #3 . reopening and one of us can close again once you are happy with the font size. @sarahmagrish
