### ISSUE TITLE
text block template creation

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#40]
Hiya! 

Trying to do a text block like we have here: http://63y.ea8.mwp.accessdomain.com/project/tenant-one/

but realizing I can't access that margin styling. Anyway to standardize that into a way I can access to drop in other pages? 

Here is how it is showing up now: 
![screen shot 2018-04-16 at 1 40 38 pm](https://user-images.githubusercontent.com/4765127/38834668-f78b8b16-417d-11e8-9964-1dc4151a294c.png)

thx!

**Comment by pollardld** [comment]
Added a new section template called 2/3 width text that can now be used on any page. 

<img width="1034" alt="screen shot 2018-04-17 at 4 42 55 pm" src="https://user-images.githubusercontent.com/2632164/38904310-7ad707bc-425e-11e8-88ba-9b556da2e9e4.png">
