### ISSUE TITLE
ecotrust logo in footer

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#41]
For some reason I can't get it to look good on retina! Can you take a look? thanks

**Comment by pollardld** [comment]
Yea this can be frustrating. The rule i use to fix is to use an image that is at least double the size i need and then constrain its width value to the width needed. 
*e.g.*: a 300px width image will use a 600px width image. 

I change the footer image to a larger one. Any other changes can be made by adjusting the width value for new image. @sarahmagrish

**Comment by ldford** [comment]
This looks good to me. @sarahmagrish did you check it?

**Comment by sarahmagrish** [comment]
yes grt! thx
