### ISSUE TITLE
picture / text blocks

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#42]
Hi David,

The home page, Venue, and About all use alternating picture and text boxes but when they stack on mobile they get out of order—you end up seeing text/text, picture/picture and it doesn't make a lot of sense. Ideas on how to address in mobile?

thanks,
Sarah

**Comment by pollardld** [comment]
Well ... 👎 

A little css to the rescue: 

```
.img-text-link:nth-of-type(2n) .fw-container-fluid > .fw-row {
    display: flex;
    flex-flow: column-reverse;
  }
```

on mobile screens ever other img-text-link section gets its img/text order switched. *e.g.*: 


| **small screen** | **large screen** |
| ---------------- | ----------------
| img / text | img / text |
| img / text | text / img |
| img / text | img / text |
