### ISSUE TITLE
footer on mobile

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#46]
Looks pretty sharp! Could just use a bit of spacing between the sections for an easier read

**Comment by ldford** [comment]
Ugh. I actually really hate the footer on mobile! I feel like things are out of order - like from top to bottom (other than the social media icons) things should be reversed? Or maybe just the Redd lockup plus ecotrust logo should be moved to the bottom (below the enews signup) and everything else stays in order, just the spacing is fixed. Don't want to make @pollardld do too much work just for a footer though!
![image](https://user-images.githubusercontent.com/6453589/39065530-f0105752-4486-11e8-8d7a-7c3de57fd113.png)

**Comment by pollardld** [comment]
Order reversed. Let me know what you think @ldford @sarahmagrish 
<img width="368" alt="screen shot 2018-04-20 at 2 36 28 pm" src="https://user-images.githubusercontent.com/2632164/39075416-5f2587f2-44aa-11e8-8730-a0772b183b76.png">

**Comment by ldford** [comment]
I like it so much better!
