### ISSUE TITLE
favicon please!

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#57]
I think @pollardld can implement if you let him know what we'd like it to be.

![image](https://user-images.githubusercontent.com/6453589/39023478-b41cb728-43ef-11e8-87df-8185d6c32079.png)

**Comment by sarahmagrish** [comment]
hi @pollardld! Can you use an svg for the favicon? If so I have one attached here. thanks, Sarah

ps. Github made me zip it

[favicon_redd_site.svg.zip](https://github.com/Ecotrust/theredd/files/1954409/favicon_redd_site.svg.zip)

**Comment by pollardld** [comment]
👍
