### ISSUE TITLE
Menu on mobile

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#62]
Do we add "home" to the mobile menu?
![image](https://user-images.githubusercontent.com/6453589/39075953-6b74c3f8-44ad-11e8-87a5-a1adcc8fb581.png)

**Comment by pollardld** [comment]
My opinion is no, because the stamp icon brings you home. This is the same as on desktop. If anyone has reason to disagree, i can add it.

**Comment by ldford** [comment]
sounds good
