### ISSUE TITLE
Hub page hero image

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#64]
Hi David! I don't know why but in Chrome on my mac the hero image on the hub page doesn't extend behind the top nav -- making it pretty hard to use the nav. 

<img width="1376" alt="screen shot 2018-05-07 at 2 27 32 am" src="https://user-images.githubusercontent.com/4765127/39695376-2eff908e-519f-11e8-822b-8b744c83fc7e.png">

I don't think it was something I did recently (although I was messing around on the page adding subtenants) as I tried to revery to an older version and the problem was still there.

thanks!
Sarah

**Comment by pollardld** [comment]
There was an extra content section above the hero image. Once i deleted that it went back to normal. It could have been added accidentally very easily just by fat fingering the keyboard, so it was probably my fault. Thanks for catching this!

<img width="600" alt="screen shot 2018-05-07 at 10 29 18 am" src="https://user-images.githubusercontent.com/2632164/39715306-b81615cc-51e1-11e8-8b5e-8df213b8ed2b.png">
