### ISSUE TITLE
Table style?

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/theredd#65]
Hi again,

I added the subtenant list in table form to the hub page (hidden at the moment in the live site) but can't seem to get the table border to go away. Can you help? thx!

**Comment by sarahmagrish** [comment]
hi @pollardld! Any chance you could check this out today?

**Comment by pollardld** [comment]
Yes, sorry for the delay. will check on this today @sarahmagrish

**Comment by pollardld** [comment]
Is this what you had in mind?

<img width="937" alt="screen shot 2018-05-09 at 10 22 13 am" src="https://user-images.githubusercontent.com/2632164/39829295-dbba05fa-5372-11e8-91f4-81e8c05f9c05.png">

**Comment by sarahmagrish** [comment]
perfect thanks! : )
