### ISSUE TITLE
Map broken

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#67]
@pollardld the google map isn't loading on any browser I go to. 

http://reddonsalmon.com/visit/#location

![image](https://user-images.githubusercontent.com/6453589/43669981-2ea931ca-973c-11e8-800d-7cfbb7a333b6.png)

**Comment by pollardld** [comment]
Google API key had been removed. Most likely deleted by accident, and good chance the accident was mine. 

Everything should be working as expected now.
