### ISSUE TITLE
Copy change for Page 2

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#7]
After Amanda's quote, replace the current 2-sentence copy with this:

The Redd on Salmon Street is a new Ecotrust development located in the heart of Portland’s historic Central Eastside, designed to support authentic local food-related enterprises in Portland, connect them to the rich producers in surrounding farmlands, and scale a robust, regional food economy across the Pacific Northwest.

**Comment by pollardld** [comment]
copy has been updated.
