### ISSUE TITLE
slight copy change - page 2

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#8]
Final copy change to page 2 graph, then we are ready for DNS switch:

The Redd on Salmon Street is a new Ecotrust development located in the heart of Portland’s historic Central Eastside that is designed to support local food enterprises, connect chefs, foodservice directors and entrepreneurs to independent farmers, ranchers and fishers in the region, and help scale a robust, regional food economy across the Pacific Northwest.

**Comment by pollardld** [comment]
text updated. making DNS switch now.

**Comment by pollardld** [comment]
text updated. making DNS switch now.
