### ISSUE TITLE
design element missing

### ISSUE THREAD

**Issue by ldford** [Ecotrust/theredd#9]
@pollardld I noticed that on FF and Chrome the arrows leading users from screen to screen have disappeared. They do appear on IE.

IE:
![image](https://cloud.githubusercontent.com/assets/6453589/24760185/c8311ba0-1a9c-11e7-8a8e-23664e4953b0.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/6453589/24760203/d3c1f1b0-1a9c-11e7-8932-b0054ba9cd32.png)

**Comment by pollardld** [comment]
:astonished: usually the other way
